"""initial

Revision ID: 74c3326c0996
Revises: 
Create Date: 2026-05-09 11:07:28.894450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74c3326c0996'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('pet_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('info_name', sa.String(length=50), nullable=True),
    sa.Column('info_host', sa.String(length=50), nullable=True),
    sa.Column('info_sex', sa.String(length=2), nullable=True),
    sa.Column('info_growth', sa.Float(), nullable=True),
    sa.Column('info_hunger', sa.Integer(), nullable=True),
    sa.Column('info_clean', sa.Integer(), nullable=True),
    sa.Column('info_health', sa.Integer(), nullable=True),
    sa.Column('info_mood', sa.Integer(), nullable=True),
    sa.Column('info_yb', sa.Integer(), nullable=True),
    sa.Column('info_intel', sa.Integer(), nullable=True),
    sa.Column('info_charm', sa.Integer(), nullable=True),
    sa.Column('info_strong', sa.Integer(), nullable=True),
    sa.Column('info_birth_day', sa.String(length=20), nullable=True),
    sa.Column('info_online_time', sa.Float(), nullable=True),
    sa.Column('info_last_login_time', sa.Integer(), nullable=True),
    sa.Column('info_online_data_time', sa.Float(), nullable=True),
    sa.Column('max_level', sa.Integer(), nullable=True),
    sa.Column('max_hunger', sa.Integer(), nullable=True),
    sa.Column('max_clean', sa.Integer(), nullable=True),
    sa.Column('max_mood', sa.Integer(), nullable=True),
    sa.Column('max_growth_rate', sa.Integer(), nullable=True),
    sa.Column('max_up_growth', sa.Integer(), nullable=True),
    sa.Column('max_next_growth', sa.Integer(), nullable=True),
    sa.Column('max_stop_growth', sa.Boolean(), nullable=True),
    sa.Column('active_option', sa.JSON(), nullable=True),
    sa.Column('active_value', sa.JSON(), nullable=True),
    sa.Column('other_options', sa.JSON(), nullable=True),
    sa.Column('fishing', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pet_data_id'), 'pet_data', ['id'], unique=False)
    op.create_index(op.f('ix_pet_data_user_id'), 'pet_data', ['user_id'], unique=True)
    op.create_table('pet_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pet_inventory_id'), 'pet_inventory', ['id'], unique=False)
    op.create_index(op.f('ix_pet_inventory_user_id'), 'pet_inventory', ['user_id'], unique=True)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_jti', sa.String(length=100), nullable=False),
    sa.Column('device_info', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_token_jti'), 'sessions', ['token_jti'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shortcuts', sa.JSON(), nullable=True),
    sa.Column('stop_growth', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_jti'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_pet_inventory_user_id'), table_name='pet_inventory')
    op.drop_index(op.f('ix_pet_inventory_id'), table_name='pet_inventory')
    op.drop_table('pet_inventory')
    op.drop_index(op.f('ix_pet_data_user_id'), table_name='pet_data')
    op.drop_index(op.f('ix_pet_data_id'), table_name='pet_data')
    op.drop_table('pet_data')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
